= trino-opa-authorizer

== Usage


=== OPA

Currently expects that Open Policy Agent is listening on http://localhost:8181. Run `opa run --log-level debug --server example.rego` in the repo folder to test an initial example.

=== Trino plugin

Assuming that you already have a Trino server set up.

1. Run `mvn package`
2. Copy (or symlink) `target/out` to `$TRINO_DIR/plugins/trino-opa-authorizer`
3. Copy (or symlink) `access-control.properties` to `$TRINO_DIR/etc/access-control.properties`
4. Start Trino

=== Tests

The tests assume that OPA is available on your path as `opa`, and can then be executed by running `mvn test`.

=== Example

The example `example.rego` allows the `admin` user to do everything. User `bob` is limited to run queries and access catalogs.

----
package trino

import future.keywords.in

default allow = false

allow {
	is_admin
}

allow {
	is_bob
	can_be_accessed_by_bob
}

is_admin() {
	input.context.identity.user == "admin"
}

is_bob() {
	input.context.identity.user == "bob"
}

can_be_accessed_by_bob() {
    input.action.operation in ["ImpersonateUser", "FilterCatalogs", "AccessCatalog", "ExecuteQuery"]
}
----

This can be tested via the Trino CLI for the `admin` user:
----
./trino-cli-377-executable.jar --server http://localhost:8080 --user=admin
----
and for the user `bob`:
----
./trino-cli-377-executable.jar --server http://localhost:8080 --user=bob
----

When logged in as `bob` you should be able to run:
----
trino> SHOW CATALOGS;
 Catalog
---------
 system
(1 row)

Query 20220419_161711_00047_bu682, FINISHED, 1 node
Splits: 1 total, 1 done (100.00%)
0.22 [0 rows, 0B] [0 rows/s, 0B/s]

----
but should get an `Access Denied` failure when e.g. showing schemas:
----
trino> SHOW SCHEMAS From system;
Query 20220419_161650_00046_bu682 failed: Access Denied: Cannot show schemas